version: '3.8'

services:
 nginx:
    image: nginx:1.19.8
    networks:
      - my-network
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx
    ports:
      - 8183:80
 web:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - my-network
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

networks:
  my-network: